# Generated by Django 2.0.7 on 2018-08-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0002_qrcoupon_is_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcoupon',
            old_name='is_acitve',
            new_name='available',
        ),
    ]
